### ISSUE TITLE
Installing the sample driver causes an error - invalid parameter for service or function

### ISSUE THREAD

**Issue by lurebat** [microsoft/Windows-rust-driver-samples#7]
The error on the device:
```
Windows cannot initialize the device driver for this hardware. (Code 37)

An invalid parameter was passed to a service or function.
```

There is this event:
```
Device ROOT\SAMPLE\0000 had a problem starting.

Driver Name: oem24.inf
Class Guid: {78a1c341-4539-11d3-b88d-00c04fad5171}
Service: ECHO_2
Lower Filters: 
Upper Filters: 
Problem: 0x25
Problem Status: 0xC000000D
```

System:
-Windows 10 VM
-DriverCertificate has been installed on the machine
-Did all the steps - including driver signing.

**Comment by wmmc88** [comment]
This is due to using W10. If you want to use W10 right now, the patch described in https://github.com/microsoft/windows-drivers-rs/issues/42#issuecomment-1905274389 is required until https://github.com/microsoft/windows-drivers-rs/issues/82 lands. 

Closing this as dupe. Tracking this issues in https://github.com/microsoft/windows-drivers-rs/issues/42
